Deployment of hello app
ClubCedille/Plateforme-Cedille pull request #154
Opened 2024-03-29 19:09 UTC by SonOfLope

### Description
Deployment of Hello app for the club App|ets : https://github.com/ApplETS/Backend-Hello/tree/main

We are currently deploying the backend of the app with a postgresql database and a redis server.
### Checklist

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

- [ ] Requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-30 15:17 UTC, Simon-Boyer requested changes
J'ai mis un changement dans le deploiement de l'app avec le security context et les limites de ressources, faudrait faire la meme chose pour le statefulset postgres et redis

2024-03-30 15:17 UTC, Simon-Boyer commented on apps/applets/hello/base/deployment.yaml
> +  namespace: applets-hello
```suggestion
```

2024-03-30 15:17 UTC, Simon-Boyer commented on apps/applets/hello/base/redis/service.yaml
> +  namespace: applets-hello
```suggestion
```

2024-03-30 15:17 UTC, Simon-Boyer commented on apps/applets/hello/base/redis/statefulset.yaml
> +  namespace: applets-hello
```suggestion
```

2024-03-30 15:17 UTC, Simon-Boyer commented on apps/applets/hello/base/service.yaml
> +  namespace: applets-hello
```suggestion
```

2024-03-30 15:17 UTC, Simon-Boyer commented on apps/applets/hello/prod/kustomization.yaml
> +
```suggestion

namespace: applets-hello

bases:
  - ../base
  
```

2024-03-30 15:17 UTC, Simon-Boyer commented on apps/applets/hello/base/deployment.yaml
> +          volumeMounts:
Adapter selon la prevision de consommation de ressources et de droits nécessaires

```suggestion
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
```

2024-03-31 19:04 UTC, SonOfLope commented
> J'ai mis un changement dans le deploiement de l'app avec le security context et les limites de ressources, faudrait faire la meme chose pour le statefulset postgres et redis

@Simon-Boyer all done!

2024-04-01 17:17 UTC, Simon-Boyer requested changes
Kustomize fails with this:

```
error: accumulating resources: accumulation err='accumulating resources from '../base/': '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base' must resolve to a file': recursed accumulation of path '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base': accumulating resources: accumulation err='accumulating resources from 'postgres/pv.yaml': evalsymlink failure on '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml' : lstat /home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml' : lstat /home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml: no such file or directory
```

Looks like `base/postgres/pv.yaml` is missing

2024-04-01 17:25 UTC, SonOfLope commented
> Kustomize fails with this:
> 
> > error: accumulating resources: accumulation err='accumulating resources from '../base/': '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base' must resolve to a file': recursed accumulation of path '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base': accumulating resources: accumulation err='accumulating resources from 'postgres/pv.yaml': evalsymlink failure on '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml' : lstat /home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml' : lstat /home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml: no such file or directory
> 
> Looks like `base/postgres/pv.yaml` is missing

oops yeah je l'ai enlever pcq avec le statefulset pv template il était pas nécessaire.

2024-04-01 17:27 UTC, SonOfLope commented
> Kustomize fails with this:
> 
> > error: accumulating resources: accumulation err='accumulating resources from '../base/': '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base' must resolve to a file': recursed accumulation of path '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base': accumulating resources: accumulation err='accumulating resources from 'postgres/pv.yaml': evalsymlink failure on '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml' : lstat /home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on '/home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml' : lstat /home/simon/Repos/Plateforme-Cedille/apps/applets/hello/base/postgres/pv.yaml: no such file or directory
> 
> Looks like `base/postgres/pv.yaml` is missing

done

2024-04-01 17:30 UTC, Simon-Boyer approved these changes

2024-04-01 17:30 UTC, merged