English 'Onboarding' and 'Complete onboarding' documentation
ClubCedille/Plateforme-Cedille pull request #261
Opened 2024-11-09 00:15 UTC by RussellJimmies

First iteration of the onboarding documentation in English.

2024-11-09 20:56 UTC, SonOfLope approved these changes
LGTM! You can add French version in same PR. 
@Endlessflow pitch in a review when you can.

2024-11-11 11:27 UTC, Endlessflow requested changes, later dismissed
This looks like it's shaping up quite nicely. Thanks for the help, @RussellJimmies. I'm glad you're the one taking care of this section. 
Having another member write it forces me to flesh out my vision of things in detail and sync it with everyone.
My hope if for this syncing process to lead to constructive discussions where we can refine the understanding of identity of the organization.

2024-11-11 11:27 UTC, Endlessflow commented on wiki/docs/en/onboarding/index.md
> +We aim to bridge the gab between the academic world and the industry by making knowledge and technology accessible to all. We promote open-source, collaboration, and Infrastructure as Code to ensure
I think this part is particularly important to nail down, so bear with me.

Technically, we don’t bridge the gap between academia and industry by making knowledge and technology accessible. 

So far (and likely for the foreseeable future), we have focused our identity on creating opportunities for members to grow by getting involved in projects. Acquiring and sharing knowledge is a natural side effect of everyone’s involvement in these learning opportunities, but it’s not the primary goal we’re pursuing.

In an ideal world, CEDILLE would evolve into a community hub where people can collaborate, gain hands-on experience, and build knowledge by working on projects that hold significant academic interest to the members or, ideally, tackle real-world challenges to benefit the ÉTS community.

This process of building confidence and skills through contributions to meaningful projects is, I believe, what can help students grow from “sheltered” learners into fully-fledged engineers. Through their work, they should gradually improve themselves and build a portfolio of case studies demonstrating how they’ve added value to the community they belong to. When they graduate and begin looking for career opportunities, this portfolio will act as evidence of the impact they've made and will, hopefully, spark conversations that lead to career advancement.

Well... at the very least, this is the vision I am trying to make a reality.

2024-11-11 11:27 UTC, Endlessflow commented on wiki/docs/en/onboarding/index.md
> +Explore the following resources for a solid introduction to the key technologies used at CEDILLE. These links offer foundational knowledge that will be helpful for the hands-on labs.
I am not against having a link of useful resources here. I do have to ask though - what exactly is our end goal with this list ? 

### Do we want to have a list of useful references for member to peruse at their leisure and refer back to ? 
if so, there is an argument to be made that maybe this list should be in its own entry page in the wiki where we slowly add the link to the useful references members can read to deepen their understanding of various topic  we deem of interest.

### Do we want to introduce the various list of technology of tools we are using ? 
(I personally think this is what we want to do)
then I suggest that we lean in hard on this and make it explicit 
for example we could say: 

> The following list is a non exhaustive list of some of the technology stacks we like to use at CEDILLE. Each item links to a small introduction to the technology that you can peruse at your leisure to get a grasp of the stack we usually work with.

and each item on the list should have a single link to a short page where the tool in question is introduced.

This is already the case for the python and go doc links which point to the page in the official doc where the technology are introduced brievely, the grav link should instead point to [What is Grav?](https://learn.getgrav.org/17/basics/what-is-grav), the hugo link should be [Introduction to Hugo](https://gohugo.io/about/introduction/), etc etc

### Something else ?
maybe ? whatever it is though I suggest that we make it so painfully clear that people don't need to think.

2024-11-11 11:27 UTC, Endlessflow commented on wiki/docs/en/onboarding/index.md
> +It's time to put into practice what you've just learnt! Click [here](./hands-on-labs/index.md) to get started with the Hands-on labs.
I have mixed feeling about this closing thought.
The hands on lab is where the learning takes place 😂
Shouldn't we close this page with something more along the lines of :

> # Moving Forward
> 
> Now that you have a clearer understanding of our community's mission and philosophy, it's time to dive in and embark on your first project. In the spirit of our club's mission—and to kickstart your journey toward becoming a fully-fledged engineer—we've crafted a hands-on lab where you'll build your own personal portfolio website and launch it live on the web.
> 
> Through this lab, you will be able to learn the basics of everything you will need to successfully start your journey with CEDILLE. But even more importantly, you will create your own personal tool to start documenting your accomplishments and setting the foundation for your future professional success.
> 
> Click [here](https://github.com/ClubCedille/Plateforme-Cedille/pull/261/hands-on-labs/index.md) to get started with the Hands-on Labs.

Or really any other closing thought as long as it 
- acknowledge that they now understand the mission of the community they are joining
- introduces the next part of the onboarding process as a personal investment. This isn't going to be some random project that they are going to be making for a cause they have no personal attachment to yet. but rather it is a first step in investing on themselves and building the tool that will allow them to (hopefully) start documenting their accomplishment on their road to success.

2025-03-28 22:41 UTC, SonOfLope commented
@RussellJimmies whenever you have time, do you think you could give some love to this PR. We have some new members that will start contributing to the wiki so and it would be nice to have your section merged :D it would also help them see if anything is missing or unclear as part of their onboarding

2025-05-13 00:25 UTC, SonOfLope approved these changes
Hell yeah the much awaited comeback. LGTM! You can please merge this and if anything on @Endlessflow side well just open an issue but this will allow get started on directing the labs

2025-05-13 00:26 UTC, SonOfLope commented
@RussellJimmies forgot to say simply translate first but you probsbly know that already

2025-05-15 23:59 UTC, SonOfLope commented
@RussellJimmies you're good to go

2025-05-16 00:10 UTC, merged

2025-05-16 00:12 UTC, RussellJimmies commented
@SonOfLope Merged and ready to onboard the masses! 🙌